---
title: "Ollama"
author: "Anne Visser"
date: "2026-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rollama)
library(ellmer)
```

## How does Ollama work

Ollama is a program that let's users use open LLM-models locally or cloud based. It needs to be downloaded through the terminal of the server or a local computer. 
The default LLM model is llama3:8b. If a user wants to use different models it can pull (download) models that are mentioned on https://ollama.com/search.
Ollama needs to be commanded through the terminal, but with certain R-packages it can be talked to through R.
There are several packages available: Rollama, ollamar and ellmer_chat_ollama. Rollama and Ollamar are quite similar but Rollama is a little more familiar for working in R. Ellmer_chat_ollama is good when using Shiny apps.

# How does querychat work with Ollama?

Querychat is a package that can be used in R or in python. The R-package brings together an LLM-client, a table in a database and system prompts (prompts with instructions for the LLM). This is presented in a user interface through a Shiny app with a chatbox. A shiny app is an R-based web application in the form of a dashboard. 
